# Required variables:
# - mysql_root_password: The password to set for the MySQL root user.
# - login_host (optional): The host to use for MySQL login (default: localhost).

- name: ansible to install pymysql
  ansible.builtin.pip:
    name:
    - PyMySQL
    executable: pip3
- name: install MySQL Server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start mysql server
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: gather MySQL server info
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
  ignore_errors: true
  register: mysql_info

- name: print mysql info
  ansible.builtin.debug:
    msg: "{{ mysql_info }}"

- name: setup MySQL root password
  community.mysql.mysql_user:
  when: "'failed' in mysql_info and mysql_info.failed"
    host_all: true
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password | default('') }}"
    login_host: "{{ login_host | default('localhost') }}"
    state: present
  when: mysql_info.failed is true